//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentsExplorer.Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentsExplorerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentsExplorerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentsExplorer.Website.Resources.DocumentsExplorerResource", typeof(DocumentsExplorerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Council Reports Count Last Three Years.
        /// </summary>
        public static string titleCouncilReportsCountChart {
            get {
                return ResourceManager.GetString("titleCouncilReportsCountChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effected Countries for {0}.
        /// </summary>
        public static string titleCountryProjectsChart {
            get {
                return ResourceManager.GetString("titleCountryProjectsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Decision.
        /// </summary>
        public static string titleLoanDecisionChart {
            get {
                return ResourceManager.GetString("titleLoanDecisionChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Decisions.
        /// </summary>
        public static string titleSectorDecisionssChart {
            get {
                return ResourceManager.GetString("titleSectorDecisionssChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string TreeNodeCompanies {
            get {
                return ResourceManager.GetString("TreeNodeCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Council Memebers.
        /// </summary>
        public static string TreeNodeCouncilMemebers {
            get {
                return ResourceManager.GetString("TreeNodeCouncilMemebers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decisions.
        /// </summary>
        public static string TreeNodeDecisions {
            get {
                return ResourceManager.GetString("TreeNodeDecisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Types.
        /// </summary>
        public static string TreeNodeDecisionTypes {
            get {
                return ResourceManager.GetString("TreeNodeDecisionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Responsibles.
        /// </summary>
        public static string TreeNodeDepartmentResponsibles {
            get {
                return ResourceManager.GetString("TreeNodeDepartmentResponsibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string TreeNodeDepartments {
            get {
                return ResourceManager.GetString("TreeNodeDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinutesOfMeeting.
        /// </summary>
        public static string TreeNodeMinutesOfMeeting {
            get {
                return ResourceManager.GetString("TreeNodeMinutesOfMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        public static string TreeNodeRounds {
            get {
                return ResourceManager.GetString("TreeNodeRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectores.
        /// </summary>
        public static string TreeNodeSectores {
            get {
                return ResourceManager.GetString("TreeNodeSectores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absents.
        /// </summary>
        public static string txtAbsents {
            get {
                return ResourceManager.GetString("txtAbsents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected Parties.
        /// </summary>
        public static string txtAffectedParties {
            get {
                return ResourceManager.GetString("txtAffectedParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Name.
        /// </summary>
        public static string txtAttachmentName {
            get {
                return ResourceManager.GetString("txtAttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string txtAttachments {
            get {
                return ResourceManager.GetString("txtAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Type.
        /// </summary>
        public static string txtAttachmentType {
            get {
                return ResourceManager.GetString("txtAttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendances.
        /// </summary>
        public static string txtAttendances {
            get {
                return ResourceManager.GetString("txtAttendances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string txtCompany {
            get {
                return ResourceManager.GetString("txtCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Description.
        /// </summary>
        public static string txtCompanyActivityDescription {
            get {
                return ResourceManager.GetString("txtCompanyActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Company.
        /// </summary>
        public static string txtCompanySelectValue {
            get {
                return ResourceManager.GetString("txtCompanySelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Date.
        /// </summary>
        public static string txtConferenceDate {
            get {
                return ResourceManager.GetString("txtConferenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Index.
        /// </summary>
        public static string txtConferenceIndex {
            get {
                return ResourceManager.GetString("txtConferenceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Location.
        /// </summary>
        public static string txtConferenceLocation {
            get {
                return ResourceManager.GetString("txtConferenceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Number.
        /// </summary>
        public static string txtConferenceNumber {
            get {
                return ResourceManager.GetString("txtConferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Year.
        /// </summary>
        public static string txtConferenceYear {
            get {
                return ResourceManager.GetString("txtConferenceYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string txtContributors {
            get {
                return ResourceManager.GetString("txtContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors Profit Percentage.
        /// </summary>
        public static string txtContributorsProfitPercentage {
            get {
                return ResourceManager.GetString("txtContributorsProfitPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Council Reports Count :  {0}.
        /// </summary>
        public static string txtCouncilReportsCount {
            get {
                return ResourceManager.GetString("txtCouncilReportsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Council Type.
        /// </summary>
        public static string txtCouncilTypeDescription {
            get {
                return ResourceManager.GetString("txtCouncilTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Council Type.
        /// </summary>
        public static string txtCouncilTypeSelectValue {
            get {
                return ResourceManager.GetString("txtCouncilTypeSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string txtCountry {
            get {
                return ResourceManager.GetString("txtCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string txtCountrySelectValue {
            get {
                return ResourceManager.GetString("txtCountrySelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Incorporation.
        /// </summary>
        public static string txtDateOfIncorporation {
            get {
                return ResourceManager.GetString("txtDateOfIncorporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Annex.
        /// </summary>
        public static string txtDecisionAnnexPath {
            get {
                return ResourceManager.GetString("txtDecisionAnnexPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Execution.
        /// </summary>
        public static string txtDecisionExecution {
            get {
                return ResourceManager.GetString("txtDecisionExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Number.
        /// </summary>
        public static string txtDecisionNO {
            get {
                return ResourceManager.GetString("txtDecisionNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision.
        /// </summary>
        public static string txtDecisionPath {
            get {
                return ResourceManager.GetString("txtDecisionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Reference.
        /// </summary>
        public static string txtDecisionReference {
            get {
                return ResourceManager.GetString("txtDecisionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Reference Preview.
        /// </summary>
        public static string txtDecisionReferencePreview {
            get {
                return ResourceManager.GetString("txtDecisionReferencePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Status.
        /// </summary>
        public static string txtDecisionStatus {
            get {
                return ResourceManager.GetString("txtDecisionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string txtDecisionSubject {
            get {
                return ResourceManager.GetString("txtDecisionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Text.
        /// </summary>
        public static string txtDecisionText {
            get {
                return ResourceManager.GetString("txtDecisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Type.
        /// </summary>
        public static string txtDecisionType {
            get {
                return ResourceManager.GetString("txtDecisionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Decision Type .
        /// </summary>
        public static string txtDecisionTypeSelectValue {
            get {
                return ResourceManager.GetString("txtDecisionTypeSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string txtDepartment {
            get {
                return ResourceManager.GetString("txtDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string txtDepartments {
            get {
                return ResourceManager.GetString("txtDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company.
        /// </summary>
        public static string txtEditCompanyTitle {
            get {
                return ResourceManager.GetString("txtEditCompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Council Member.
        /// </summary>
        public static string txtEditCouncilMemberTitle {
            get {
                return ResourceManager.GetString("txtEditCouncilMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Decision.
        /// </summary>
        public static string txtEditDecision {
            get {
                return ResourceManager.GetString("txtEditDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Minutes Of Meeting.
        /// </summary>
        public static string txtEditMinutesOfMeetingTitle {
            get {
                return ResourceManager.GetString("txtEditMinutesOfMeetingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Round.
        /// </summary>
        public static string txtEditRoundTitle {
            get {
                return ResourceManager.GetString("txtEditRoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Decison.
        /// </summary>
        public static string txtExecuteDecisonTitle {
            get {
                return ResourceManager.GetString("txtExecuteDecisonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Notes.
        /// </summary>
        public static string txtExecutionNotes {
            get {
                return ResourceManager.GetString("txtExecutionNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date.
        /// </summary>
        public static string txtFinishDate {
            get {
                return ResourceManager.GetString("txtFinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string txtFromDate {
            get {
                return ResourceManager.GetString("txtFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string txtFullName {
            get {
                return ResourceManager.GetString("txtFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active?.
        /// </summary>
        public static string txtIsActive {
            get {
                return ResourceManager.GetString("txtIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Date.
        /// </summary>
        public static string txtJoiningDate {
            get {
                return ResourceManager.GetString("txtJoiningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Words.
        /// </summary>
        public static string txtKeyWords {
            get {
                return ResourceManager.GetString("txtKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Reserve.
        /// </summary>
        public static string txtLegalReserve {
            get {
                return ResourceManager.GetString("txtLegalReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string txtLocation {
            get {
                return ResourceManager.GetString("txtLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string txtLogInTitle {
            get {
                return ResourceManager.GetString("txtLogInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Category.
        /// </summary>
        public static string txtMainCategory {
            get {
                return ResourceManager.GetString("txtMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Main Category.
        /// </summary>
        public static string txtMainCategorySelectValue {
            get {
                return ResourceManager.GetString("txtMainCategorySelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Reserve.
        /// </summary>
        public static string txtMainReserve {
            get {
                return ResourceManager.GetString("txtMainReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Date.
        /// </summary>
        public static string txtMeetingDate {
            get {
                return ResourceManager.GetString("txtMeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Summary.
        /// </summary>
        public static string txtMeetingSummary {
            get {
                return ResourceManager.GetString("txtMeetingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Company.
        /// </summary>
        public static string txtNewCompanyTitle {
            get {
                return ResourceManager.GetString("txtNewCompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Council Member.
        /// </summary>
        public static string txtNewCouncilMemberTitle {
            get {
                return ResourceManager.GetString("txtNewCouncilMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Decision.
        /// </summary>
        public static string txtNewDecisionTitle {
            get {
                return ResourceManager.GetString("txtNewDecisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Minutes Of Meeting.
        /// </summary>
        public static string txtNewMinutesOfMeetingTitle {
            get {
                return ResourceManager.GetString("txtNewMinutesOfMeetingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Round.
        /// </summary>
        public static string txtNewRoundTitle {
            get {
                return ResourceManager.GetString("txtNewRoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestine Support.
        /// </summary>
        public static string txtPalestineSupport {
            get {
                return ResourceManager.GetString("txtPalestineSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph Index.
        /// </summary>
        public static string txtParagraphIndex {
            get {
                return ResourceManager.GetString("txtParagraphIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Photo.
        /// </summary>
        public static string txtPhotoPath {
            get {
                return ResourceManager.GetString("txtPhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string txtPosition {
            get {
                return ResourceManager.GetString("txtPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Value.
        /// </summary>
        public static string txtProgramValue {
            get {
                return ResourceManager.GetString("txtProgramValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Value In Dollar.
        /// </summary>
        public static string txtProgramValueInDollar {
            get {
                return ResourceManager.GetString("txtProgramValueInDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Previews.
        /// </summary>
        public static string txtProjectTitle {
            get {
                return ResourceManager.GetString("txtProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Reference Decision.
        /// </summary>
        public static string txtReferenceDecisionSelectValue {
            get {
                return ResourceManager.GetString("txtReferenceDecisionSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refernce Decision Number.
        /// </summary>
        public static string txtRefrenceDecisionNumber {
            get {
                return ResourceManager.GetString("txtRefrenceDecisionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string txtRoundDescription {
            get {
                return ResourceManager.GetString("txtRoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Number.
        /// </summary>
        public static string txtRoundNumber {
            get {
                return ResourceManager.GetString("txtRoundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Round.
        /// </summary>
        public static string txtRoundSelectValue {
            get {
                return ResourceManager.GetString("txtRoundSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Text.
        /// </summary>
        public static string txtSearch {
            get {
                return ResourceManager.GetString("txtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string txtSector {
            get {
                return ResourceManager.GetString("txtSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors.
        /// </summary>
        public static string txtSectors {
            get {
                return ResourceManager.GetString("txtSectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        public static string txtSubCategory {
            get {
                return ResourceManager.GetString("txtSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sub Category .
        /// </summary>
        public static string txtSubCategorySelectValue {
            get {
                return ResourceManager.GetString("txtSubCategorySelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Execution Date.
        /// </summary>
        public static string txtSuggestedExecutionDate {
            get {
                return ResourceManager.GetString("txtSuggestedExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string txtToDate {
            get {
                return ResourceManager.GetString("txtToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string txtUserName {
            get {
                return ResourceManager.GetString("txtUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Activity Sectors.
        /// </summary>
        public static string txtViewAllActivitySectors {
            get {
                return ResourceManager.GetString("txtViewAllActivitySectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Companies.
        /// </summary>
        public static string txtViewAllCompanies {
            get {
                return ResourceManager.GetString("txtViewAllCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Council Memebers.
        /// </summary>
        public static string txtViewAllCouncilMemebers {
            get {
                return ResourceManager.GetString("txtViewAllCouncilMemebers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Decision Types.
        /// </summary>
        public static string txtViewAllDecisionTypes {
            get {
                return ResourceManager.GetString("txtViewAllDecisionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Minutes Of Meeting.
        /// </summary>
        public static string txtViewAllMinutesOfMeeting {
            get {
                return ResourceManager.GetString("txtViewAllMinutesOfMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Reports.
        /// </summary>
        public static string txtViewAllReports {
            get {
                return ResourceManager.GetString("txtViewAllReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Rounds.
        /// </summary>
        public static string txtViewAllRounds {
            get {
                return ResourceManager.GetString("txtViewAllRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Council Reports of {0}.
        /// </summary>
        public static string txtViewCouncilReports {
            get {
                return ResourceManager.GetString("txtViewCouncilReports", resourceCulture);
            }
        }
    }
}
